

FROM node:25.6.1-alpine3.23 as dev
WORKDIR /app
COPY package.json package.json
RUN npm i 
COPY src src
COPY tsconfig.json tsconfig.json
EXPOSE 3000 

CMD npm run dev

FROM node:25.6.1-alpine3.23 as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY src src
COPY tsconfig.json tsconfig.json
RUN npm run build

FROM node:25.6.1-alpine3.23 as production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./
RUN npm ci --only=production
EXPOSE 3000
CMD ["npm", "start"]