

FROM node:25.6.1-alpine3.23 as dev
WORKDIR /app
COPY package.json package.json
RUN npm i 
COPY src src
COPY tsconfig.json tsconfig.json
EXPOSE 3000 

CMD npm run dev

##
##FROM node:25.6.1-alpine3.23 as build 
##WORKDIR /app
##COPY package.json package.json
##RUN npm i 
##COPY src src
##COPY tsconfig.json tsconfig.json
##EXPOSE 3000 
##CMD npm run build